services:
  postgres:
    image: postgres:16.4-alpine
    container_name: postgres
    restart: unless-stopped
    hostname: postgres
    volumes:

      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spending-tracker

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/spending-tracker
      - ORIGIN_URL=http://localhost:5173
    depends_on:
      - postgres
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /code
          ignore:
            - .venv/
        - action: rebuild
          path: ./backend/poetry.lock

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /code
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package-lock.json

volumes:
  postgres_data:
