services:
  postgres:
    image: postgres:16.4-alpine
    container_name: postgres
    restart: unless-stopped
    hostname: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spending-tracker

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/spending-tracker
      - ORIGIN_URL=http://127.0.0.1:5173
    depends_on:
      - postgres

volumes:
  postgres_data:
