"""Initial migration

Revision ID: 053660a0e682
Revises:
Create Date: 2025-07-15 22:16:40.322861

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "053660a0e682"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
