"""Remove denormalized category_name and filter_name from transaction model

Revision ID: 52c901f38474
Revises: e775d573c2bb
Create Date: 2025-07-25 21:55:06.841291

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52c901f38474"
down_revision: str | Sequence[str] | None = "e775d573c2bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "category_name", schema="report")
    op.drop_column("transaction", "filter_name", schema="report")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction",
        sa.Column("filter_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="report",
    )
    op.add_column(
        "transaction",
        sa.Column("category_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="report",
    )
    # ### end Alembic commands ###
