"""Add denormalized category_name and filter_name to transaction

Revision ID: e775d573c2bb
Revises: 053660a0e682
Create Date: 2025-07-15 22:26:07.877254

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e775d573c2bb"
down_revision: str | Sequence[str] | None = "053660a0e682"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("category_name", sa.String(), nullable=True), schema="report")
    op.add_column("transaction", sa.Column("filter_name", sa.String(), nullable=True), schema="report")
    # Populate filter_name from filter table
    op.execute("""
        UPDATE report.transaction t
        SET filter_name = f.name
        FROM report.filter f
        WHERE t.filter_id = f.id;
    """)
    # Populate category_name from category table via filter
    op.execute("""
        UPDATE report.transaction t
        SET category_name = c.name
        FROM report.filter f
        JOIN report.category c ON f.category_id = c.id
        WHERE t.filter_id = f.id;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "filter_name", schema="report")
    op.drop_column("transaction", "category_name", schema="report")
    # ### end Alembic commands ###
