"""Add jsonb fields

Revision ID: ae2302096d52
Revises: 127d5718371c
Create Date: 2026-03-02 23:31:53.148996

"""


from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ae2302096d52"
down_revision: str | Sequence[str] | None = "127d5718371c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("report", sa.Column("schema_version", sa.Integer(), nullable=True), schema="report")
    op.add_column("report", sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema="report")

    op.execute("UPDATE report.report SET schema_version = 1 WHERE schema_version IS NULL")
    op.alter_column("report", "schema_version", existing_type=sa.Integer(), nullable=False, schema="report")

    op.add_column("transaction", sa.Column("schema_version", sa.Integer(), nullable=True), schema="report")
    op.add_column("transaction", sa.Column("type", sa.String(), nullable=True), schema="report")
    op.add_column("transaction", sa.Column("product", sa.String(), nullable=True), schema="report")
    op.add_column("transaction", sa.Column("currency", sa.String(), nullable=True), schema="report")
    op.add_column("transaction", sa.Column("state", sa.String(), nullable=True), schema="report")
    op.add_column("transaction", sa.Column("balance", sa.Float(), nullable=True), schema="report")
    op.add_column(
        "transaction",
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema="report",
    )
    op.alter_column(
        "transaction",
        "fee",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
        schema="report",
    )

    op.execute("UPDATE report.transaction SET schema_version = 1 WHERE schema_version IS NULL")
    op.alter_column("transaction", "schema_version", existing_type=sa.Integer(), nullable=False, schema="report")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "raw_data", schema="report")
    op.drop_column("transaction", "balance", schema="report")
    op.drop_column("transaction", "state", schema="report")
    op.drop_column("transaction", "currency", schema="report")
    op.drop_column("transaction", "product", schema="report")
    op.drop_column("transaction", "type", schema="report")
    op.drop_column("transaction", "schema_version", schema="report")
    op.alter_column(
        "transaction",
        "fee",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        schema="report",
    )
    op.drop_column("report", "data", schema="report")
    op.drop_column("report", "schema_version", schema="report")
    # ### end Alembic commands ###
